//Create random number - max 20
function randomNumber(max) {
    return Math.floor(Math.random() * max);  
}

//Assign two random numbers
let firstNumber = randomNumber(20);
let secondNumber = randomNumber(20);

//Assign variables to hidden elements
let winnerMessage = document.getElementById('winner-message');
let winnerConfetti = document.getElementById('winner-confetti');
let newGame = document.getElementById('new-game');

//Generate equation using first and second number
function generateEquation() {
    document.getElementById('first-number').innerHTML = firstNumber;
    document.getElementById('second-number').innerHTML = secondNumber;
}

let userAnswer = document.getElementById('user-input');
window.onload = userAnswer.focus()


//Every Time the window loads, a new question is generated
window.onload = generateEquation;

//Add 10 to score, if score = 100, display game winning message
let score = 0;
function addToScore(){
    score += 10;
    document.getElementById('score').innerHTML = score;
    if (score == 100){
        winnerMessage.style.display = 'inline';
        winnerConfetti.style.display = 'inline';
        newGame.style.display = 'inline';
    }
}

//reset score
function resetScore(){
    score = 0;
    document.getElementById('score').innerHTML = score;
    winnerMessage.style.display = 'none';
    winnerConfetti.style.display = 'none';
    newGame.style.display = 'none';
    window.onload = userAnswer.focus()

}

//When user answers question correctly, a check and 'Great Job!' is displayed for 2 seconds
function correctAnswer(){
    let praise = document.getElementById('praise');
    let check = document.getElementById('check');
    addToScore();
    check.style.display = 'inline';
    praise.style.display = 'inline';
    setTimeout(() => {
        check.style.display = 'none';
        praise.style.display = 'none';

    }, 2000);
    window.onload = userAnswer.focus()

}

function clickPress(event) {
    if (event.keyCode == 13) {
       evaluated(); 
}

}
//When user answers question incorrectly, an x and 'Incorrect! Start Over!' is displayed for 2 seconds
function incorrectAnswer() {
    let startOver = document.getElementById('start-over');
    let wrong = document.getElementById('wrong');
    startOver.style.display = 'inline';
    wrong.style.display = 'inline';
    resetScore();
    setTimeout(() => {
        startOver.style.display = 'none';
        wrong.style.display = 'none';
    }, 2000);
    window.onload = userAnswer.focus()

}

//Empty Array to store answers generated by API
const answers = []

//Use API to evaluate equation
function evaluated(){
    //Access user answer
    let userAnswer = document.getElementById('user-input').value;
    //Pass numbers into API to evaluate
    let url = 'http://api.mathjs.org/v4/?expr=' + encodeURIComponent(firstNumber+secondNumber);
    //Check to see if user answered the question correctly
    axios.get(url).then(response => {
        answers.push(response.data);
        if (userAnswer == answers[answers.length-1]){
            correctAnswer();
        } else {
            incorrectAnswer();
        }
    }, err=> {
        console.log(err)
    })
    //Get next question 
    setTimeout(() => {
        firstNumber = randomNumber(20);
        secondNumber = randomNumber(20);
        document.getElementById('first-number').innerHTML = firstNumber;
        document.getElementById('second-number').innerHTML = secondNumber;
        document.getElementById('user-input').value = '';
    }, 2000);
    }





   
    